version: '3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  api:
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    volumes:
      - ./api/src:/app/api/src
    expose:
      - 3000
    ports:
      - '3000:3000'
    command: node dist/index.js

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/src:/app/src
    expose:
      - 80
    ports:
      - '8000:80'

volumes:
  db:
