version: '3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  api:
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/api/src
    expose:
      - 3000
    ports:
      - '3000:3000'
    command: npm run start:watch

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./client/src:/app/src
    expose:
      - 3000
    ports:
      - '8000:3000'
    command: npm start

volumes:
  db:
